spring.application.name=backend
database.filename.missions=src/main/resources/database/missionPlans.json
database.filename.modules=src/main/resources/database/modules.json
database.filename.module.types=src/main/resources/database/moduleTypes.json
database.filename.users=src/main/resources/database/users.json
