spring.application.name=backend
database.filename.missions=backend/src/main/resources/database/missionPlans.json
database.filename.modules=backend/src/main/resources/database/modules.json
database.filename.module.types=src/main/resources/database/moduleTypes.json
database.filename.users=backend/src/main/resources/database/users.json
database.filename.event.catalog=backend/src/main/resources/database/eventCatalog.json
database.filename.schedules=backend/src/main/resources/database/schedules.json
database.filename.scenario.drafts=backend/src/main/resources/database/scenarioDrafts.json
database.filename.analysis.payload=backend/src/main/resources/database/payloadSessions.json
database.filename.analysis.nominal=backend/src/main/resources/database/nominalSessions.json
database.filename.analysis.scenarios=backend/src/main/resources/database/scenariosSessions.json
